server.port=10200
spring.application.name=zuul-server

#Eureka configuration
eureka.instance.leaseRenewalIntervalInSeconds = 10
eureka.client.registryFetchIntervalSeconds=5
eureka.client.serviceUrl.defaultZone=http://localhost:10210/eureka
spring.cloud.service-registry.auto-registration.enabled=true
eureka.client.enabled=true
1eureka.client.serviceUrl.registerWithEureka=true

lombok.anyConstructor.suppressConstructorProperties = true



#Zuul Configuration
# A prefix that can added to beginning of all requests.
#zuul.prefix=/api

# Disable accessing services using service name (i.e. gallery-service).
# They should be only accessed through the path defined below.
zuul.ignored-services=*

# Map paths to services
zuul.routes.gallery-service.path=/gallery/**
zuul.routes.gallery-service.service-id=gallery-manager

zuul.routes.image-service.path=/image/**
zuul.routes.image-service.service-id=image-service

zuul.routes.book-manager.path=/book-manager/**
zuul.routes.book-manager.service-id=book-manager

zuul.routes.auth-service.path=/auth/**
zuul.routes.auth-service.service-id=auth-manager

zuul.routes.remote-library.path=/remote/**
zuul.routes.remote-library.service-id=remote-library



#zuul.routes.auth-service.strip-prefix=false

# Exclude authorization from sensitive headers
zuul.routes.auth-service.sensitive-headers=Cookie,Set-Cookie 

