spring.application.name=image-service
server.port=10220
#eureka.client.service-url.default-zone=http://localhost:10210/eureka
eureka.client.serviceUrl.defaultZone=http://localhost:10210/eureka
lombok.anyConstructor.suppressConstructorProperties = true
