
# Give a name to the eureka server
spring.application.name=eureka-server

# default port for eureka server
server.port=10210

# eureka by default will register itself as a client. So, we need to set it to false.
# What's a client server? See other microservices (image, gallery, auth, etc).

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.pattern.console=
logging.path=logs
logging.file=${logging.path}/bm.log
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n